import { dirname } from "node:path";
import { fileURLToPath } from "node:url";
import { FlatCompat } from "@eslint/eslintrc";

const __dirname = dirname(fileURLToPath(import.meta.url));

const compat = new FlatCompat({
  baseDirectory: __dirname,
});

const eslintConfig = [
  {
    ignores: [
      ".next/**",
      "coverage/**",
      // Plain Service Worker script (ServiceWorkerGlobalScope: self/caches/
      // fetch), not part of the Next.js/React/TS app — a different runtime
      // than this config is set up for.
      "public/sw.js",
      // Auto-generated by `next dev`/`next build`, not checked into git
      // (see .gitignore) and explicitly "should not be edited".
      "next-env.d.ts",
    ],
  },
  ...compat.extends("next/core-web-vitals", "next/typescript"),
  {
    rules: {
      // Leading-underscore params are this codebase's existing convention
      // for intentionally-unused callback args in test mocks (see
      // components/BarcodeScanner.test.tsx).
      "@typescript-eslint/no-unused-vars": ["warn", { argsIgnorePattern: "^_" }],
      // Product photos come from Open Food Facts' arbitrary, product-specific
      // CDN hosts (components/screens/ResultScreen.tsx, ProductSearch.tsx) —
      // next/image would need every such host allow-listed for a hobby app
      // with no image-optimization budget to speak of.
      "@next/next/no-img-element": "off",
    },
  },
  {
    // app/layout.tsx is the App Router root layout, not a Pages Router
    // page — this rule's "only loads for a single page" warning is written
    // for pages/_document.js and doesn't apply here (the font link already
    // loads for every route).
    files: ["app/layout.tsx"],
    rules: {
      "@next/next/no-page-custom-font": "off",
    },
  },
];

export default eslintConfig;
